title: Adam Spotton
intro: Random musings about software engineering, data science, linux, and other stuff.

# Avatar must be uploaded to theme "img" folder.
intro_avatar: avatar.png
author:
  name: Adam Spotton
  email: 
  footer: © 2019 Adam Spotton. All rights reserved.
  footer2: 
  url: 
  url2: 
metadata:
    description: 'Random musings about software engineering, data science, linux, and other stuff.'

# Main Menu
menu:
  - text: External link
    link: "#" 

social: 
  - icon: github
    link: "https://github.com/aspotton/"
  - icon: linkedin
    link: "https://www.linkedin.com/in/adamspotton/"
  - icon: twitter
    link: "https://twitter.com/AdamSpotton"
